package com.minibudget.config;

public enum ExpenseEnum {

    ULASIM, FATURA, EGITIM, EGLENCE, VERGI, YEMEK, HEDIYE, SAGLIK,KIRA,AIDAT,TAMIR,COCUK,KISISELBAKIM,
    ALISVERIS,SEYAHAT,BORC,GIYIM,DIGER;

}
